'use client'

import { RefreshCw, TrendingDown, AlertTriangle, CheckCircle2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { ForecastsTable } from '@/components/forecasts/ForecastsTable'
import { useRestockAlerts } from '@/hooks/useForecasts'

export default function ForecastsPage() {
  const { data: alerts, isLoading, refetch, isFetching, error } = useRestockAlerts()

  const criticalCount = (alerts ?? []).filter((a) => a.daysUntilStockout <= 7).length
  const warningCount = (alerts ?? []).filter(
    (a) => a.daysUntilStockout > 7 && a.daysUntilStockout <= 14
  ).length
  const healthyCount = (alerts ?? []).filter((a) => a.daysUntilStockout > 14).length

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-100">ML Forecasts</h1>
          <p className="mt-1 text-sm text-slate-500">
            AI-powered restock predictions — refreshes every 5 minutes
          </p>
        </div>
        <Button variant="ghost" size="sm" onClick={() => refetch()} disabled={isFetching}
          className="text-slate-400 hover:text-slate-200">
          <RefreshCw className={`mr-2 h-4 w-4 ${isFetching ? 'animate-spin' : ''}`} />
          Refresh
        </Button>
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <Card className="border-red-500/20 bg-red-500/5">
          <CardContent className="flex items-center gap-4 p-5">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-red-500/10">
              <AlertTriangle className="h-5 w-5 text-red-400" />
            </div>
            <div>
              <p className="text-2xl font-bold text-red-400">{isLoading ? '—' : criticalCount}</p>
              <p className="text-xs text-slate-500">Critical (&lt;7 days)</p>
            </div>
          </CardContent>
        </Card>
        <Card className="border-amber-500/20 bg-amber-500/5">
          <CardContent className="flex items-center gap-4 p-5">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-amber-500/10">
              <TrendingDown className="h-5 w-5 text-amber-400" />
            </div>
            <div>
              <p className="text-2xl font-bold text-amber-400">{isLoading ? '—' : warningCount}</p>
              <p className="text-xs text-slate-500">Warning (7–14 days)</p>
            </div>
          </CardContent>
        </Card>
        <Card className="border-emerald-500/20 bg-emerald-500/5">
          <CardContent className="flex items-center gap-4 p-5">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-500/10">
              <CheckCircle2 className="h-5 w-5 text-emerald-400" />
            </div>
            <div>
              <p className="text-2xl font-bold text-emerald-400">{isLoading ? '—' : healthyCount}</p>
              <p className="text-xs text-slate-500">Manageable (&gt;14 days)</p>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="rounded-lg border border-slate-800 bg-slate-900/50">
        {isLoading ? (
          <div className="space-y-2 p-6">
            {Array.from({ length: 6 }).map((_, i) => (
              <Skeleton key={i} className="h-14 w-full" />
            ))}
          </div>
        ) : error ? (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <p className="text-red-400 font-medium">Failed to load forecast alerts</p>
            <p className="text-xs text-slate-500 mt-1">
              {error instanceof Error ? error.message : 'Check ML Restock service on port 8085'}
            </p>
          </div>
        ) : (
          <ForecastsTable alerts={alerts ?? []} />
        )}
      </div>

      <p className="text-xs text-slate-600 text-center">
        Alerts generated by ML Restock Engine · Service: localhost:8085
      </p>
    </div>
  )
}
