server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/orders/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"

        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/products/**, /api/inventory/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 30
                redis-rate-limiter.burstCapacity: 60
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/payments/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"

        - id: ml-restock-engine
          uri: ${ML_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/forecasts/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"

      default-filters:
        - AddResponseHeader=X-Gateway-Version, 1.0.0
        - AddResponseHeader=X-Response-Time, ${spring.application.name}

jwt:
  secret: ${JWT_SECRET:smart-inventory-platform-secret-key-must-be-at-least-256-bits-long}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, gateway
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.inventory.gateway: DEBUG
    org.springframework.cloud.gateway: INFO
